name: flutter_hololive_app
description: hololive app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  firebase_core: "0.5.0"
  firebase_database: "^4.0.0"

  timetable: ^0.2.8
  time_machine: ^0.9.13

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
